# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2026-02-11 05:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0002_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entry',
            options={'verbose_name_plural': 'entties'},
        ),
    ]
